### ISSUE TITLE
Build Failures on ROS 2 Buildfarm for Rolling

### ISSUE THREAD

**Issue by Yadunund** [ros2/rmw_gurumdds#16]
An update to [rmw_dds_common](https://github.com/ros2/rmw_dds_common/pull/73) has led to build regresses in `rmw_gurumdds_cpp` on the ROS 2 Buildfarm for Rolling. See
- https://build.ros2.org/view/Rbin_uJ64/job/Rbin_uJ64__rmw_gurumdds_cpp__ubuntu_jammy_amd64__binary/

Full Log from [Console Output](https://build.ros2.org/view/Rbin_uJ64/job/Rbin_uJ64__rmw_gurumdds_cpp__ubuntu_jammy_amd64__binary/137/console) :

<details>
  <summary>Click me</summary>
  
```bash
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:448:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   448 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_node_deleted(rmw_context_impl_t*, const rmw_node_t*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:479:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   479 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_publisher_created(rmw_context_impl_t*, const rmw_node_t*, GurumddsPublisherInfo*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:497:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   497 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_publisher_deleted(rmw_context_impl_t*, const rmw_node_t*, GurumddsPublisherInfo*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:530:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   530 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_subscriber_created(rmw_context_impl_t*, const rmw_node_t*, GurumddsSubscriberInfo*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:557:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   557 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_subscriber_deleted(rmw_context_impl_t*, const rmw_node_t*, GurumddsSubscriberInfo*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:590:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   590 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_service_created(rmw_context_impl_t*, const rmw_node_t*, GurumddsServiceInfo*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:617:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   617 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_service_deleted(rmw_context_impl_t*, const rmw_node_t*, GurumddsServiceInfo*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:683:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   683 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_client_created(rmw_context_impl_t*, const rmw_node_t*, GurumddsClientInfo*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:723:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   723 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_client_deleted(rmw_context_impl_t*, const rmw_node_t*, GurumddsClientInfo*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:787:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   787 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_on_participant_info(rmw_context_impl_t*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:846:57: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   846 |       std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                         ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_add_participant(rmw_context_impl_t*, const dds_GUID_t*, const char*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:873:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   873 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_remove_participant(rmw_context_impl_t*, const dds_GUID_t*)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:892:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   892 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_add_remote_entity(rmw_context_impl_t*, const dds_GUID_t*, const dds_GUID_t*, const char*, const char*, const dds_ReliabilityQosPolicy*, const dds_DurabilityQosPolicy*, const dds_DeadlineQosPolicy*, const dds_LivelinessQosPolicy*, const dds_LifespanQosPolicy*, bool)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:912:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   912 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp: In function ‘rmw_ret_t graph_remove_entity(rmw_context_impl_t*, const dds_GUID_t*, bool)’:
15:07:22 /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:958:53: error: ‘std::mutex rmw_dds_common::Context::node_update_mutex’ is private within this context
15:07:22   958 |   std::lock_guard<std::mutex> guard(ctx->common_ctx.node_update_mutex);
15:07:22       |                                                     ^~~~~~~~~~~~~~~~~
15:07:22 In file included from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/include/rmw_gurumdds_cpp/rmw_context_impl.hpp:37,
15:07:22                  from /tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/src/graph_cache.cpp:25:
15:07:22 /opt/ros/rolling/include/rmw_dds_common/rmw_dds_common/context.hpp:198:14: note: declared private here
15:07:22   198 |   std::mutex node_update_mutex;
15:07:22       |              ^~~~~~~~~~~~~~~~~
15:07:22 make[4]: *** [CMakeFiles/rmw_gurumdds_cpp.dir/build.make:527: CMakeFiles/rmw_gurumdds_cpp.dir/src/graph_cache.cpp.o] Error 1
15:07:22 make[4]: Leaving directory '/tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/.obj-x86_64-linux-gnu'
15:07:22 make[3]: *** [CMakeFiles/Makefile2:140: CMakeFiles/rmw_gurumdds_cpp.dir/all] Error 2
15:07:22 make[3]: Leaving directory '/tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/.obj-x86_64-linux-gnu'
15:07:22 make[2]: *** [Makefile:149: all] Error 2
15:07:22 make[2]: Leaving directory '/tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0/.obj-x86_64-linux-gnu'
15:07:22 dh_auto_build: error: cd .obj-x86_64-linux-gnu && make -j1 VERBOSE=1 returned exit code 2
15:07:22 make[1]: *** [debian/rules:44: override_dh_auto_build] Error 25
15:07:22 make[1]: Leaving directory '/tmp/binarydeb/ros-rolling-rmw-gurumdds-cpp-4.2.0'
15:07:22 make: *** [debian/rules:27: build] Error 2
15:07:22 dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
15:07:22 Traceback (most recent call last):
15:07:22   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 149, in build_binarydeb
15:07:22     subprocess.check_call(cmd, cwd=source_dir, env=env)
15:07:22   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
15:07:22     raise CalledProcessError(retcode, cmd)
15:07:22 subprocess.CalledProcessError: Command '['dpkg-buildpackage', '-b', '-us', '-uc']' returned non-zero exit status 2.
15:07:22 # END SUBSECTION
```
</details>

Rolling sync is blocked as a result of this regression.

**Comment by Yadunund** [comment]
Hi @YoungJin-gurum could you please look at addressing this issue? It would help unblock the Rolling sync that is long overdue :)
